[package]
name = "checklist"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
